[package]
name = "document_validator_core"
version = "0.1.1"
edition = "2021"
description = "Required dependencies for document_validator and document_validator_macros"
license = "MIT"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2.0.28", features = ["full", "extra-traits"] }
