[package]
name = "document_validator_macros"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Macros used by document_validator"

[lib]
proc-macro = true

[dependencies]
document_validator_core = { version = "0.1.0", path= "../core" }
